name: Deploy Laravel Fast

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Checkout Code
      uses: actions/checkout@v4

    - name: ⚙️ Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        tools: composer:v2

    - name: 📦 Install Deployer
      run: composer global require deployer/deployer

    - name: 🔑 Setup SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: 🔓 Trust VPS Host Key
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts

    - name: 🚀 Deploy to aaPanel
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
      run: ~/.composer/vendor/bin/dep deploy -vvv